// Code generated by protoc-gen-go. DO NOT EDIT.
// source: P_Server.proto

package Adoter_Asset

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
//消息类型
//
type MSG_TYPE int32

const (
	MSG_TYPE_MSG_TYPE_AOI_NULL         MSG_TYPE = 0
	MSG_TYPE_MSG_TYPE_AOI_ENTER        MSG_TYPE = 30001
	MSG_TYPE_MSG_TYPE_AOI_LEAVE        MSG_TYPE = 30002
	MSG_TYPE_MSG_TYPE_AOI_MOVE         MSG_TYPE = 30003
	MSG_TYPE_MSG_TYPE_HEART_BEAT       MSG_TYPE = 30004
	MSG_TYPE_MSG_TYPE_KICK_OUT         MSG_TYPE = 30005
	MSG_TYPE_MSG_TYPE_META_DS_MESSAGE  MSG_TYPE = 30006
	MSG_TYPE_MSG_TYPE_META_MAIL        MSG_TYPE = 30007
	MSG_TYPE_MSG_TYPE_LEAVE_LEVEL      MSG_TYPE = 30008
	MSG_TYPE_MSG_TYPE_LEAVE_DUNGEON    MSG_TYPE = 30009
	MSG_TYPE_MSG_TYPE_ROOM_STARTGAME   MSG_TYPE = 30010
	MSG_TYPE_MSG_TYPE_SEND_MAIL        MSG_TYPE = 30011
	MSG_TYPE_MSG_TYPE_ENTERGAME        MSG_TYPE = 30012
	MSG_TYPE_MSG_TYPE_FRIEND_OPER      MSG_TYPE = 30013
	MSG_TYPE_MSG_TYPE_ENTER_DUNGEON    MSG_TYPE = 30014
	MSG_TYPE_MSG_TYPE_ENTER_LEVEL      MSG_TYPE = 30015
	MSG_TYPE_MSG_TYPE_LEVEL_SETTLEMENT MSG_TYPE = 30016
	MSG_TYPE_MSG_TYPE_CHANGE_LINE      MSG_TYPE = 30017
	MSG_TYPE_MSG_TYPE_WJJJ_LEVEL_IDS   MSG_TYPE = 30018
)

var MSG_TYPE_name = map[int32]string{
	0:     "MSG_TYPE_AOI_NULL",
	30001: "MSG_TYPE_AOI_ENTER",
	30002: "MSG_TYPE_AOI_LEAVE",
	30003: "MSG_TYPE_AOI_MOVE",
	30004: "MSG_TYPE_HEART_BEAT",
	30005: "MSG_TYPE_KICK_OUT",
	30006: "MSG_TYPE_META_DS_MESSAGE",
	30007: "MSG_TYPE_META_MAIL",
	30008: "MSG_TYPE_LEAVE_LEVEL",
	30009: "MSG_TYPE_LEAVE_DUNGEON",
	30010: "MSG_TYPE_ROOM_STARTGAME",
	30011: "MSG_TYPE_SEND_MAIL",
	30012: "MSG_TYPE_ENTERGAME",
	30013: "MSG_TYPE_FRIEND_OPER",
	30014: "MSG_TYPE_ENTER_DUNGEON",
	30015: "MSG_TYPE_ENTER_LEVEL",
	30016: "MSG_TYPE_LEVEL_SETTLEMENT",
	30017: "MSG_TYPE_CHANGE_LINE",
	30018: "MSG_TYPE_WJJJ_LEVEL_IDS",
}

var MSG_TYPE_value = map[string]int32{
	"MSG_TYPE_AOI_NULL":         0,
	"MSG_TYPE_AOI_ENTER":        30001,
	"MSG_TYPE_AOI_LEAVE":        30002,
	"MSG_TYPE_AOI_MOVE":         30003,
	"MSG_TYPE_HEART_BEAT":       30004,
	"MSG_TYPE_KICK_OUT":         30005,
	"MSG_TYPE_META_DS_MESSAGE":  30006,
	"MSG_TYPE_META_MAIL":        30007,
	"MSG_TYPE_LEAVE_LEVEL":      30008,
	"MSG_TYPE_LEAVE_DUNGEON":    30009,
	"MSG_TYPE_ROOM_STARTGAME":   30010,
	"MSG_TYPE_SEND_MAIL":        30011,
	"MSG_TYPE_ENTERGAME":        30012,
	"MSG_TYPE_FRIEND_OPER":      30013,
	"MSG_TYPE_ENTER_DUNGEON":    30014,
	"MSG_TYPE_ENTER_LEVEL":      30015,
	"MSG_TYPE_LEVEL_SETTLEMENT": 30016,
	"MSG_TYPE_CHANGE_LINE":      30017,
	"MSG_TYPE_WJJJ_LEVEL_IDS":   30018,
}

func (x MSG_TYPE) String() string {
	return proto.EnumName(MSG_TYPE_name, int32(x))
}

func (MSG_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{0}
}

type MERGE_ZONE_TYPE int32

const (
	MERGE_ZONE_TYPE_MERGE_ZONE_TYPE_NULL      MERGE_ZONE_TYPE = 0
	MERGE_ZONE_TYPE_MERGE_ZONE_TYPE_RANK      MERGE_ZONE_TYPE = 1
	MERGE_ZONE_TYPE_MERGE_ZONE_TYPE_CLAN      MERGE_ZONE_TYPE = 2
	MERGE_ZONE_TYPE_MERGE_ZONE_TYPE_PARTY     MERGE_ZONE_TYPE = 3
	MERGE_ZONE_TYPE_MERGE_ZONE_TYPE_PVP       MERGE_ZONE_TYPE = 4
	MERGE_ZONE_TYPE_MERGE_ZONE_TYPE_LIANYIN   MERGE_ZONE_TYPE = 5
	MERGE_ZONE_TYPE_MERGE_ZONE_TYPE_HONORWALL MERGE_ZONE_TYPE = 6
	MERGE_ZONE_TYPE_MERGE_ZONE_TYPE_CHAT      MERGE_ZONE_TYPE = 7
	MERGE_ZONE_TYPE_MERGE_ZONE_TYPE_BAN       MERGE_ZONE_TYPE = 8
)

var MERGE_ZONE_TYPE_name = map[int32]string{
	0: "MERGE_ZONE_TYPE_NULL",
	1: "MERGE_ZONE_TYPE_RANK",
	2: "MERGE_ZONE_TYPE_CLAN",
	3: "MERGE_ZONE_TYPE_PARTY",
	4: "MERGE_ZONE_TYPE_PVP",
	5: "MERGE_ZONE_TYPE_LIANYIN",
	6: "MERGE_ZONE_TYPE_HONORWALL",
	7: "MERGE_ZONE_TYPE_CHAT",
	8: "MERGE_ZONE_TYPE_BAN",
}

var MERGE_ZONE_TYPE_value = map[string]int32{
	"MERGE_ZONE_TYPE_NULL":      0,
	"MERGE_ZONE_TYPE_RANK":      1,
	"MERGE_ZONE_TYPE_CLAN":      2,
	"MERGE_ZONE_TYPE_PARTY":     3,
	"MERGE_ZONE_TYPE_PVP":       4,
	"MERGE_ZONE_TYPE_LIANYIN":   5,
	"MERGE_ZONE_TYPE_HONORWALL": 6,
	"MERGE_ZONE_TYPE_CHAT":      7,
	"MERGE_ZONE_TYPE_BAN":       8,
}

func (x MERGE_ZONE_TYPE) String() string {
	return proto.EnumName(MERGE_ZONE_TYPE_name, int32(x))
}

func (MERGE_ZONE_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{1}
}

//玩家定时更新类型
type UPDATE_PERIOD_TYPE int32

const (
	UPDATE_PERIOD_TYPE_UPDATE_PERIOD_TYPE_NULL   UPDATE_PERIOD_TYPE = 0
	UPDATE_PERIOD_TYPE_UPDATE_PERIOD_TYPE_DAY    UPDATE_PERIOD_TYPE = 1
	UPDATE_PERIOD_TYPE_UPDATE_PERIOD_TYPE_HOUR   UPDATE_PERIOD_TYPE = 2
	UPDATE_PERIOD_TYPE_UPDATE_PERIOD_TYPE_CUSTOM UPDATE_PERIOD_TYPE = 3
)

var UPDATE_PERIOD_TYPE_name = map[int32]string{
	0: "UPDATE_PERIOD_TYPE_NULL",
	1: "UPDATE_PERIOD_TYPE_DAY",
	2: "UPDATE_PERIOD_TYPE_HOUR",
	3: "UPDATE_PERIOD_TYPE_CUSTOM",
}

var UPDATE_PERIOD_TYPE_value = map[string]int32{
	"UPDATE_PERIOD_TYPE_NULL":   0,
	"UPDATE_PERIOD_TYPE_DAY":    1,
	"UPDATE_PERIOD_TYPE_HOUR":   2,
	"UPDATE_PERIOD_TYPE_CUSTOM": 3,
}

func (x UPDATE_PERIOD_TYPE) String() string {
	return proto.EnumName(UPDATE_PERIOD_TYPE_name, int32(x))
}

func (UPDATE_PERIOD_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{2}
}

//英雄技能属性来自
type SKILL_ADDON_FROM_TYPE int32

const (
	SKILL_ADDON_FROM_TYPE_SKILL_ADDON_FROM_TYPE_NULL       SKILL_ADDON_FROM_TYPE = 0
	SKILL_ADDON_FROM_TYPE_SKILL_ADDON_FROM_TYPE_SKILL_CARD SKILL_ADDON_FROM_TYPE = 1
	SKILL_ADDON_FROM_TYPE_SKILL_ADDON_FROM_TYPE_EXPERIENCE SKILL_ADDON_FROM_TYPE = 2
	SKILL_ADDON_FROM_TYPE_SKILL_ADDON_FROM_TYPE_ITEM       SKILL_ADDON_FROM_TYPE = 3
)

var SKILL_ADDON_FROM_TYPE_name = map[int32]string{
	0: "SKILL_ADDON_FROM_TYPE_NULL",
	1: "SKILL_ADDON_FROM_TYPE_SKILL_CARD",
	2: "SKILL_ADDON_FROM_TYPE_EXPERIENCE",
	3: "SKILL_ADDON_FROM_TYPE_ITEM",
}

var SKILL_ADDON_FROM_TYPE_value = map[string]int32{
	"SKILL_ADDON_FROM_TYPE_NULL":       0,
	"SKILL_ADDON_FROM_TYPE_SKILL_CARD": 1,
	"SKILL_ADDON_FROM_TYPE_EXPERIENCE": 2,
	"SKILL_ADDON_FROM_TYPE_ITEM":       3,
}

func (x SKILL_ADDON_FROM_TYPE) String() string {
	return proto.EnumName(SKILL_ADDON_FROM_TYPE_name, int32(x))
}

func (SKILL_ADDON_FROM_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{3}
}

//玩家座次
type POSITION_TYPE int32

const (
	POSITION_TYPE_POSITION_TYPE_NULL  POSITION_TYPE = 0
	POSITION_TYPE_POSITION_TYPE_EAST  POSITION_TYPE = 1
	POSITION_TYPE_POSITION_TYPE_SOUTH POSITION_TYPE = 2
	POSITION_TYPE_POSITION_TYPE_WEST  POSITION_TYPE = 3
	POSITION_TYPE_POSITION_TYPE_NORTH POSITION_TYPE = 4
)

var POSITION_TYPE_name = map[int32]string{
	0: "POSITION_TYPE_NULL",
	1: "POSITION_TYPE_EAST",
	2: "POSITION_TYPE_SOUTH",
	3: "POSITION_TYPE_WEST",
	4: "POSITION_TYPE_NORTH",
}

var POSITION_TYPE_value = map[string]int32{
	"POSITION_TYPE_NULL":  0,
	"POSITION_TYPE_EAST":  1,
	"POSITION_TYPE_SOUTH": 2,
	"POSITION_TYPE_WEST":  3,
	"POSITION_TYPE_NORTH": 4,
}

func (x POSITION_TYPE) String() string {
	return proto.EnumName(POSITION_TYPE_name, int32(x))
}

func (POSITION_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{4}
}

//玩家状态
type PLAYER_STATUS int32

const (
	PLAYER_STATUS_PLAYER_STATUS_INITIAL      PLAYER_STATUS = 0
	PLAYER_STATUS_PLAYER_STATUS_CLOSEWAIT    PLAYER_STATUS = 1
	PLAYER_STATUS_PLAYER_STATUS_CLOSED       PLAYER_STATUS = 2
	PLAYER_STATUS_PLAYER_STATUS_LOST_CONNECT PLAYER_STATUS = 3
	PLAYER_STATUS_PLAYER_STATUS_RECONNECT    PLAYER_STATUS = 4
	PLAYER_STATUS_PLAYER_STATUS_ONLINE       PLAYER_STATUS = 5
	PLAYER_STATUS_PLAYER_STATUS_PENDING      PLAYER_STATUS = 6
	PLAYER_STATUS_PLAYER_STATUS_INGAME       PLAYER_STATUS = 7
)

var PLAYER_STATUS_name = map[int32]string{
	0: "PLAYER_STATUS_INITIAL",
	1: "PLAYER_STATUS_CLOSEWAIT",
	2: "PLAYER_STATUS_CLOSED",
	3: "PLAYER_STATUS_LOST_CONNECT",
	4: "PLAYER_STATUS_RECONNECT",
	5: "PLAYER_STATUS_ONLINE",
	6: "PLAYER_STATUS_PENDING",
	7: "PLAYER_STATUS_INGAME",
}

var PLAYER_STATUS_value = map[string]int32{
	"PLAYER_STATUS_INITIAL":      0,
	"PLAYER_STATUS_CLOSEWAIT":    1,
	"PLAYER_STATUS_CLOSED":       2,
	"PLAYER_STATUS_LOST_CONNECT": 3,
	"PLAYER_STATUS_RECONNECT":    4,
	"PLAYER_STATUS_ONLINE":       5,
	"PLAYER_STATUS_PENDING":      6,
	"PLAYER_STATUS_INGAME":       7,
}

func (x PLAYER_STATUS) String() string {
	return proto.EnumName(PLAYER_STATUS_name, int32(x))
}

func (PLAYER_STATUS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{5}
}

type GPULevel int32

const (
	GPULevel_GPULevel_High   GPULevel = 0
	GPULevel_GPULevel_Midium GPULevel = 1
	GPULevel_GPULevel_Low    GPULevel = 2
)

var GPULevel_name = map[int32]string{
	0: "GPULevel_High",
	1: "GPULevel_Midium",
	2: "GPULevel_Low",
}

var GPULevel_value = map[string]int32{
	"GPULevel_High":   0,
	"GPULevel_Midium": 1,
	"GPULevel_Low":    2,
}

func (x GPULevel) String() string {
	return proto.EnumName(GPULevel_name, int32(x))
}

func (GPULevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{6}
}

//
//消息队列
//
type MsgItem struct {
	MessageId            int64    `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	TypeT                int32    `protobuf:"varint,2,opt,name=type_t,json=typeT,proto3" json:"type_t,omitempty"`
	Priority             int32    `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Sender               int64    `protobuf:"varint,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver             int64    `protobuf:"varint,5,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Time                 int32    `protobuf:"varint,6,opt,name=time,proto3" json:"time,omitempty"`
	Delay                int32    `protobuf:"varint,7,opt,name=delay,proto3" json:"delay,omitempty"`
	Content              []byte   `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgItem) Reset()         { *m = MsgItem{} }
func (m *MsgItem) String() string { return proto.CompactTextString(m) }
func (*MsgItem) ProtoMessage()    {}
func (*MsgItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{0}
}

func (m *MsgItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgItem.Unmarshal(m, b)
}
func (m *MsgItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgItem.Marshal(b, m, deterministic)
}
func (m *MsgItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgItem.Merge(m, src)
}
func (m *MsgItem) XXX_Size() int {
	return xxx_messageInfo_MsgItem.Size(m)
}
func (m *MsgItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgItem.DiscardUnknown(m)
}

var xxx_messageInfo_MsgItem proto.InternalMessageInfo

func (m *MsgItem) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *MsgItem) GetTypeT() int32 {
	if m != nil {
		return m.TypeT
	}
	return 0
}

func (m *MsgItem) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *MsgItem) GetSender() int64 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *MsgItem) GetReceiver() int64 {
	if m != nil {
		return m.Receiver
	}
	return 0
}

func (m *MsgItem) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *MsgItem) GetDelay() int32 {
	if m != nil {
		return m.Delay
	}
	return 0
}

func (m *MsgItem) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

//
//消息队列
//
//可以用于存盘
//
type MsgItems struct {
	Items                []*MsgItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MsgItems) Reset()         { *m = MsgItems{} }
func (m *MsgItems) String() string { return proto.CompactTextString(m) }
func (*MsgItems) ProtoMessage()    {}
func (*MsgItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{1}
}

func (m *MsgItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgItems.Unmarshal(m, b)
}
func (m *MsgItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgItems.Marshal(b, m, deterministic)
}
func (m *MsgItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgItems.Merge(m, src)
}
func (m *MsgItems) XXX_Size() int {
	return xxx_messageInfo_MsgItems.Size(m)
}
func (m *MsgItems) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgItems.DiscardUnknown(m)
}

var xxx_messageInfo_MsgItems proto.InternalMessageInfo

func (m *MsgItems) GetItems() []*MsgItem {
	if m != nil {
		return m.Items
	}
	return nil
}

//玩家名称
type FamilyName struct {
	Name                 [][]byte `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FamilyName) Reset()         { *m = FamilyName{} }
func (m *FamilyName) String() string { return proto.CompactTextString(m) }
func (*FamilyName) ProtoMessage()    {}
func (*FamilyName) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{2}
}

func (m *FamilyName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FamilyName.Unmarshal(m, b)
}
func (m *FamilyName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FamilyName.Marshal(b, m, deterministic)
}
func (m *FamilyName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FamilyName.Merge(m, src)
}
func (m *FamilyName) XXX_Size() int {
	return xxx_messageInfo_FamilyName.Size(m)
}
func (m *FamilyName) XXX_DiscardUnknown() {
	xxx_messageInfo_FamilyName.DiscardUnknown(m)
}

var xxx_messageInfo_FamilyName proto.InternalMessageInfo

func (m *FamilyName) GetName() [][]byte {
	if m != nil {
		return m.Name
	}
	return nil
}

type WomanName struct {
	Name                 [][]byte `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WomanName) Reset()         { *m = WomanName{} }
func (m *WomanName) String() string { return proto.CompactTextString(m) }
func (*WomanName) ProtoMessage()    {}
func (*WomanName) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{3}
}

func (m *WomanName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WomanName.Unmarshal(m, b)
}
func (m *WomanName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WomanName.Marshal(b, m, deterministic)
}
func (m *WomanName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WomanName.Merge(m, src)
}
func (m *WomanName) XXX_Size() int {
	return xxx_messageInfo_WomanName.Size(m)
}
func (m *WomanName) XXX_DiscardUnknown() {
	xxx_messageInfo_WomanName.DiscardUnknown(m)
}

var xxx_messageInfo_WomanName proto.InternalMessageInfo

func (m *WomanName) GetName() [][]byte {
	if m != nil {
		return m.Name
	}
	return nil
}

type ManName struct {
	Name                 [][]byte `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManName) Reset()         { *m = ManName{} }
func (m *ManName) String() string { return proto.CompactTextString(m) }
func (*ManName) ProtoMessage()    {}
func (*ManName) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{4}
}

func (m *ManName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManName.Unmarshal(m, b)
}
func (m *ManName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManName.Marshal(b, m, deterministic)
}
func (m *ManName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManName.Merge(m, src)
}
func (m *ManName) XXX_Size() int {
	return xxx_messageInfo_ManName.Size(m)
}
func (m *ManName) XXX_DiscardUnknown() {
	xxx_messageInfo_ManName.DiscardUnknown(m)
}

var xxx_messageInfo_ManName proto.InternalMessageInfo

func (m *ManName) GetName() [][]byte {
	if m != nil {
		return m.Name
	}
	return nil
}

//白名单
type WhiteList struct {
	Open                 bool     `protobuf:"varint,1,opt,name=open,proto3" json:"open,omitempty"`
	IpAddress            [][]byte `protobuf:"bytes,2,rep,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WhiteList) Reset()         { *m = WhiteList{} }
func (m *WhiteList) String() string { return proto.CompactTextString(m) }
func (*WhiteList) ProtoMessage()    {}
func (*WhiteList) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{5}
}

func (m *WhiteList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhiteList.Unmarshal(m, b)
}
func (m *WhiteList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhiteList.Marshal(b, m, deterministic)
}
func (m *WhiteList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhiteList.Merge(m, src)
}
func (m *WhiteList) XXX_Size() int {
	return xxx_messageInfo_WhiteList.Size(m)
}
func (m *WhiteList) XXX_DiscardUnknown() {
	xxx_messageInfo_WhiteList.DiscardUnknown(m)
}

var xxx_messageInfo_WhiteList proto.InternalMessageInfo

func (m *WhiteList) GetOpen() bool {
	if m != nil {
		return m.Open
	}
	return false
}

func (m *WhiteList) GetIpAddress() [][]byte {
	if m != nil {
		return m.IpAddress
	}
	return nil
}

//黑名单
type BlackList struct {
	Open                 bool     `protobuf:"varint,1,opt,name=open,proto3" json:"open,omitempty"`
	IpAddress            [][]byte `protobuf:"bytes,2,rep,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlackList) Reset()         { *m = BlackList{} }
func (m *BlackList) String() string { return proto.CompactTextString(m) }
func (*BlackList) ProtoMessage()    {}
func (*BlackList) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{6}
}

func (m *BlackList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlackList.Unmarshal(m, b)
}
func (m *BlackList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlackList.Marshal(b, m, deterministic)
}
func (m *BlackList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlackList.Merge(m, src)
}
func (m *BlackList) XXX_Size() int {
	return xxx_messageInfo_BlackList.Size(m)
}
func (m *BlackList) XXX_DiscardUnknown() {
	xxx_messageInfo_BlackList.DiscardUnknown(m)
}

var xxx_messageInfo_BlackList proto.InternalMessageInfo

func (m *BlackList) GetOpen() bool {
	if m != nil {
		return m.Open
	}
	return false
}

func (m *BlackList) GetIpAddress() [][]byte {
	if m != nil {
		return m.IpAddress
	}
	return nil
}

//任务系统参数
type EventPara struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemCount            int64    `protobuf:"varint,2,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventPara) Reset()         { *m = EventPara{} }
func (m *EventPara) String() string { return proto.CompactTextString(m) }
func (*EventPara) ProtoMessage()    {}
func (*EventPara) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{7}
}

func (m *EventPara) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventPara.Unmarshal(m, b)
}
func (m *EventPara) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventPara.Marshal(b, m, deterministic)
}
func (m *EventPara) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventPara.Merge(m, src)
}
func (m *EventPara) XXX_Size() int {
	return xxx_messageInfo_EventPara.Size(m)
}
func (m *EventPara) XXX_DiscardUnknown() {
	xxx_messageInfo_EventPara.DiscardUnknown(m)
}

var xxx_messageInfo_EventPara proto.InternalMessageInfo

func (m *EventPara) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *EventPara) GetItemCount() int64 {
	if m != nil {
		return m.ItemCount
	}
	return 0
}

type MergeZoneElement struct {
	MergeType            MERGE_ZONE_TYPE `protobuf:"varint,1,opt,name=merge_type,json=mergeType,proto3,enum=Adoter.Asset.MERGE_ZONE_TYPE" json:"merge_type,omitempty"`
	ZoneList             []int64         `protobuf:"varint,2,rep,packed,name=zone_list,json=zoneList,proto3" json:"zone_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MergeZoneElement) Reset()         { *m = MergeZoneElement{} }
func (m *MergeZoneElement) String() string { return proto.CompactTextString(m) }
func (*MergeZoneElement) ProtoMessage()    {}
func (*MergeZoneElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{8}
}

func (m *MergeZoneElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MergeZoneElement.Unmarshal(m, b)
}
func (m *MergeZoneElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MergeZoneElement.Marshal(b, m, deterministic)
}
func (m *MergeZoneElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MergeZoneElement.Merge(m, src)
}
func (m *MergeZoneElement) XXX_Size() int {
	return xxx_messageInfo_MergeZoneElement.Size(m)
}
func (m *MergeZoneElement) XXX_DiscardUnknown() {
	xxx_messageInfo_MergeZoneElement.DiscardUnknown(m)
}

var xxx_messageInfo_MergeZoneElement proto.InternalMessageInfo

func (m *MergeZoneElement) GetMergeType() MERGE_ZONE_TYPE {
	if m != nil {
		return m.MergeType
	}
	return MERGE_ZONE_TYPE_MERGE_ZONE_TYPE_NULL
}

func (m *MergeZoneElement) GetZoneList() []int64 {
	if m != nil {
		return m.ZoneList
	}
	return nil
}

//世界全局数据
type World struct {
	ZoneId                int32               `protobuf:"varint,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	UpdateDayTime         int32               `protobuf:"varint,2,opt,name=update_day_time,json=updateDayTime,proto3" json:"update_day_time,omitempty"`
	UpdateWeekTime        int32               `protobuf:"varint,3,opt,name=update_week_time,json=updateWeekTime,proto3" json:"update_week_time,omitempty"`
	UpdateMonthTime       int32               `protobuf:"varint,4,opt,name=update_month_time,json=updateMonthTime,proto3" json:"update_month_time,omitempty"`
	FirstBuySn            int32               `protobuf:"varint,5,opt,name=first_buy_sn,json=firstBuySn,proto3" json:"first_buy_sn,omitempty"`
	BoyCount              int64               `protobuf:"varint,6,opt,name=boy_count,json=boyCount,proto3" json:"boy_count,omitempty"`
	GirlCount             int64               `protobuf:"varint,7,opt,name=girl_count,json=girlCount,proto3" json:"girl_count,omitempty"`
	OpenServerTime        int32               `protobuf:"varint,8,opt,name=open_server_time,json=openServerTime,proto3" json:"open_server_time,omitempty"`
	OpenserverNotifyCount int32               `protobuf:"varint,9,opt,name=openserver_notify_count,json=openserverNotifyCount,proto3" json:"openserver_notify_count,omitempty"`
	MergeList             []*MergeZoneElement `protobuf:"bytes,10,rep,name=merge_list,json=mergeList,proto3" json:"merge_list,omitempty"`
	MergeZoneTime         int32               `protobuf:"varint,11,opt,name=merge_zone_time,json=mergeZoneTime,proto3" json:"merge_zone_time,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}            `json:"-"`
	XXX_unrecognized      []byte              `json:"-"`
	XXX_sizecache         int32               `json:"-"`
}

func (m *World) Reset()         { *m = World{} }
func (m *World) String() string { return proto.CompactTextString(m) }
func (*World) ProtoMessage()    {}
func (*World) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{9}
}

func (m *World) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_World.Unmarshal(m, b)
}
func (m *World) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_World.Marshal(b, m, deterministic)
}
func (m *World) XXX_Merge(src proto.Message) {
	xxx_messageInfo_World.Merge(m, src)
}
func (m *World) XXX_Size() int {
	return xxx_messageInfo_World.Size(m)
}
func (m *World) XXX_DiscardUnknown() {
	xxx_messageInfo_World.DiscardUnknown(m)
}

var xxx_messageInfo_World proto.InternalMessageInfo

func (m *World) GetZoneId() int32 {
	if m != nil {
		return m.ZoneId
	}
	return 0
}

func (m *World) GetUpdateDayTime() int32 {
	if m != nil {
		return m.UpdateDayTime
	}
	return 0
}

func (m *World) GetUpdateWeekTime() int32 {
	if m != nil {
		return m.UpdateWeekTime
	}
	return 0
}

func (m *World) GetUpdateMonthTime() int32 {
	if m != nil {
		return m.UpdateMonthTime
	}
	return 0
}

func (m *World) GetFirstBuySn() int32 {
	if m != nil {
		return m.FirstBuySn
	}
	return 0
}

func (m *World) GetBoyCount() int64 {
	if m != nil {
		return m.BoyCount
	}
	return 0
}

func (m *World) GetGirlCount() int64 {
	if m != nil {
		return m.GirlCount
	}
	return 0
}

func (m *World) GetOpenServerTime() int32 {
	if m != nil {
		return m.OpenServerTime
	}
	return 0
}

func (m *World) GetOpenserverNotifyCount() int32 {
	if m != nil {
		return m.OpenserverNotifyCount
	}
	return 0
}

func (m *World) GetMergeList() []*MergeZoneElement {
	if m != nil {
		return m.MergeList
	}
	return nil
}

func (m *World) GetMergeZoneTime() int32 {
	if m != nil {
		return m.MergeZoneTime
	}
	return 0
}

//离线玩家邮件缓存
type MailCache struct {
	List                 []*SendMail `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MailCache) Reset()         { *m = MailCache{} }
func (m *MailCache) String() string { return proto.CompactTextString(m) }
func (*MailCache) ProtoMessage()    {}
func (*MailCache) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{10}
}

func (m *MailCache) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailCache.Unmarshal(m, b)
}
func (m *MailCache) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailCache.Marshal(b, m, deterministic)
}
func (m *MailCache) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailCache.Merge(m, src)
}
func (m *MailCache) XXX_Size() int {
	return xxx_messageInfo_MailCache.Size(m)
}
func (m *MailCache) XXX_DiscardUnknown() {
	xxx_messageInfo_MailCache.DiscardUnknown(m)
}

var xxx_messageInfo_MailCache proto.InternalMessageInfo

func (m *MailCache) GetList() []*SendMail {
	if m != nil {
		return m.List
	}
	return nil
}

//封禁玩家列表
type BanPlayerList struct {
	List                 []int64  `protobuf:"varint,1,rep,packed,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BanPlayerList) Reset()         { *m = BanPlayerList{} }
func (m *BanPlayerList) String() string { return proto.CompactTextString(m) }
func (*BanPlayerList) ProtoMessage()    {}
func (*BanPlayerList) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{11}
}

func (m *BanPlayerList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BanPlayerList.Unmarshal(m, b)
}
func (m *BanPlayerList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BanPlayerList.Marshal(b, m, deterministic)
}
func (m *BanPlayerList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BanPlayerList.Merge(m, src)
}
func (m *BanPlayerList) XXX_Size() int {
	return xxx_messageInfo_BanPlayerList.Size(m)
}
func (m *BanPlayerList) XXX_DiscardUnknown() {
	xxx_messageInfo_BanPlayerList.DiscardUnknown(m)
}

var xxx_messageInfo_BanPlayerList proto.InternalMessageInfo

func (m *BanPlayerList) GetList() []int64 {
	if m != nil {
		return m.List
	}
	return nil
}

type Redis_BanChat struct {
	PlayerId             int64    `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Timestamp            int32    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Redis_BanChat) Reset()         { *m = Redis_BanChat{} }
func (m *Redis_BanChat) String() string { return proto.CompactTextString(m) }
func (*Redis_BanChat) ProtoMessage()    {}
func (*Redis_BanChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{12}
}

func (m *Redis_BanChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Redis_BanChat.Unmarshal(m, b)
}
func (m *Redis_BanChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Redis_BanChat.Marshal(b, m, deterministic)
}
func (m *Redis_BanChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Redis_BanChat.Merge(m, src)
}
func (m *Redis_BanChat) XXX_Size() int {
	return xxx_messageInfo_Redis_BanChat.Size(m)
}
func (m *Redis_BanChat) XXX_DiscardUnknown() {
	xxx_messageInfo_Redis_BanChat.DiscardUnknown(m)
}

var xxx_messageInfo_Redis_BanChat proto.InternalMessageInfo

func (m *Redis_BanChat) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *Redis_BanChat) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

//在线玩家统计
type OnlineStatistics struct {
	OnlinePlayerCount    int64    `protobuf:"varint,1,opt,name=online_player_count,json=onlinePlayerCount,proto3" json:"online_player_count,omitempty"`
	OnlineTotalTime      int64    `protobuf:"varint,2,opt,name=online_total_time,json=onlineTotalTime,proto3" json:"online_total_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnlineStatistics) Reset()         { *m = OnlineStatistics{} }
func (m *OnlineStatistics) String() string { return proto.CompactTextString(m) }
func (*OnlineStatistics) ProtoMessage()    {}
func (*OnlineStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{13}
}

func (m *OnlineStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineStatistics.Unmarshal(m, b)
}
func (m *OnlineStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineStatistics.Marshal(b, m, deterministic)
}
func (m *OnlineStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineStatistics.Merge(m, src)
}
func (m *OnlineStatistics) XXX_Size() int {
	return xxx_messageInfo_OnlineStatistics.Size(m)
}
func (m *OnlineStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineStatistics proto.InternalMessageInfo

func (m *OnlineStatistics) GetOnlinePlayerCount() int64 {
	if m != nil {
		return m.OnlinePlayerCount
	}
	return 0
}

func (m *OnlineStatistics) GetOnlineTotalTime() int64 {
	if m != nil {
		return m.OnlineTotalTime
	}
	return 0
}

//活动数据缓存
type ActivityCache struct {
	List                 map[uint64]*ActivityElement `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ActivityCache) Reset()         { *m = ActivityCache{} }
func (m *ActivityCache) String() string { return proto.CompactTextString(m) }
func (*ActivityCache) ProtoMessage()    {}
func (*ActivityCache) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{14}
}

func (m *ActivityCache) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivityCache.Unmarshal(m, b)
}
func (m *ActivityCache) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivityCache.Marshal(b, m, deterministic)
}
func (m *ActivityCache) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivityCache.Merge(m, src)
}
func (m *ActivityCache) XXX_Size() int {
	return xxx_messageInfo_ActivityCache.Size(m)
}
func (m *ActivityCache) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivityCache.DiscardUnknown(m)
}

var xxx_messageInfo_ActivityCache proto.InternalMessageInfo

func (m *ActivityCache) GetList() map[uint64]*ActivityElement {
	if m != nil {
		return m.List
	}
	return nil
}

//离线聊天数据缓存
type PlayerChat struct {
	List                 []*Chat  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerChat) Reset()         { *m = PlayerChat{} }
func (m *PlayerChat) String() string { return proto.CompactTextString(m) }
func (*PlayerChat) ProtoMessage()    {}
func (*PlayerChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{15}
}

func (m *PlayerChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerChat.Unmarshal(m, b)
}
func (m *PlayerChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerChat.Marshal(b, m, deterministic)
}
func (m *PlayerChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerChat.Merge(m, src)
}
func (m *PlayerChat) XXX_Size() int {
	return xxx_messageInfo_PlayerChat.Size(m)
}
func (m *PlayerChat) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerChat.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerChat proto.InternalMessageInfo

func (m *PlayerChat) GetList() []*Chat {
	if m != nil {
		return m.List
	}
	return nil
}

//玩家临时属性，不存盘
type PlayerProp struct {
	Position             POSITION_TYPE  `protobuf:"varint,1,opt,name=position,proto3,enum=Adoter.Asset.POSITION_TYPE" json:"position,omitempty"`
	RoomId               int64          `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	LoadType             LOAD_TYPE      `protobuf:"varint,3,opt,name=load_type,json=loadType,proto3,enum=Adoter.Asset.LOAD_TYPE" json:"load_type,omitempty"`
	GameOperState        GAME_OPER_TYPE `protobuf:"varint,4,opt,name=game_oper_state,json=gameOperState,proto3,enum=Adoter.Asset.GAME_OPER_TYPE" json:"game_oper_state,omitempty"`
	PaiOperCount         int32          `protobuf:"varint,5,opt,name=pai_oper_count,json=paiOperCount,proto3" json:"pai_oper_count,omitempty"`
	HasTinged            bool           `protobuf:"varint,6,opt,name=has_tinged,json=hasTinged,proto3" json:"has_tinged,omitempty"`
	Offline              bool           `protobuf:"varint,7,opt,name=offline,proto3" json:"offline,omitempty"`
	VoiceMemberId        int64          `protobuf:"varint,8,opt,name=voice_member_id,json=voiceMemberId,proto3" json:"voice_member_id,omitempty"`
	Beilv                int32          `protobuf:"varint,9,opt,name=beilv,proto3" json:"beilv,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PlayerProp) Reset()         { *m = PlayerProp{} }
func (m *PlayerProp) String() string { return proto.CompactTextString(m) }
func (*PlayerProp) ProtoMessage()    {}
func (*PlayerProp) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{16}
}

func (m *PlayerProp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerProp.Unmarshal(m, b)
}
func (m *PlayerProp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerProp.Marshal(b, m, deterministic)
}
func (m *PlayerProp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerProp.Merge(m, src)
}
func (m *PlayerProp) XXX_Size() int {
	return xxx_messageInfo_PlayerProp.Size(m)
}
func (m *PlayerProp) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerProp.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerProp proto.InternalMessageInfo

func (m *PlayerProp) GetPosition() POSITION_TYPE {
	if m != nil {
		return m.Position
	}
	return POSITION_TYPE_POSITION_TYPE_NULL
}

func (m *PlayerProp) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *PlayerProp) GetLoadType() LOAD_TYPE {
	if m != nil {
		return m.LoadType
	}
	return LOAD_TYPE_LOAD_TYPE_NULL
}

func (m *PlayerProp) GetGameOperState() GAME_OPER_TYPE {
	if m != nil {
		return m.GameOperState
	}
	return GAME_OPER_TYPE_GAME_OPER_TYPE_NULL
}

func (m *PlayerProp) GetPaiOperCount() int32 {
	if m != nil {
		return m.PaiOperCount
	}
	return 0
}

func (m *PlayerProp) GetHasTinged() bool {
	if m != nil {
		return m.HasTinged
	}
	return false
}

func (m *PlayerProp) GetOffline() bool {
	if m != nil {
		return m.Offline
	}
	return false
}

func (m *PlayerProp) GetVoiceMemberId() int64 {
	if m != nil {
		return m.VoiceMemberId
	}
	return 0
}

func (m *PlayerProp) GetBeilv() int32 {
	if m != nil {
		return m.Beilv
	}
	return 0
}

//列表显示英雄信息
type ServerListHeroElement struct {
	Account              []byte   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	PlayerId             uint64   `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	HeroId               int32    `protobuf:"varint,3,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
	HeroLevel            int32    `protobuf:"varint,4,opt,name=hero_level,json=heroLevel,proto3" json:"hero_level,omitempty"`
	Frame                int32    `protobuf:"varint,5,opt,name=frame,proto3" json:"frame,omitempty"`
	Skin                 int32    `protobuf:"varint,6,opt,name=skin,proto3" json:"skin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerListHeroElement) Reset()         { *m = ServerListHeroElement{} }
func (m *ServerListHeroElement) String() string { return proto.CompactTextString(m) }
func (*ServerListHeroElement) ProtoMessage()    {}
func (*ServerListHeroElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{17}
}

func (m *ServerListHeroElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerListHeroElement.Unmarshal(m, b)
}
func (m *ServerListHeroElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerListHeroElement.Marshal(b, m, deterministic)
}
func (m *ServerListHeroElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerListHeroElement.Merge(m, src)
}
func (m *ServerListHeroElement) XXX_Size() int {
	return xxx_messageInfo_ServerListHeroElement.Size(m)
}
func (m *ServerListHeroElement) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerListHeroElement.DiscardUnknown(m)
}

var xxx_messageInfo_ServerListHeroElement proto.InternalMessageInfo

func (m *ServerListHeroElement) GetAccount() []byte {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *ServerListHeroElement) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *ServerListHeroElement) GetHeroId() int32 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *ServerListHeroElement) GetHeroLevel() int32 {
	if m != nil {
		return m.HeroLevel
	}
	return 0
}

func (m *ServerListHeroElement) GetFrame() int32 {
	if m != nil {
		return m.Frame
	}
	return 0
}

func (m *ServerListHeroElement) GetSkin() int32 {
	if m != nil {
		return m.Skin
	}
	return 0
}

type SeverListHero struct {
	List                 []*ServerListHeroElement `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	MaxLevelElement      *ServerListHeroElement   `protobuf:"bytes,2,opt,name=max_level_element,json=maxLevelElement,proto3" json:"max_level_element,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SeverListHero) Reset()         { *m = SeverListHero{} }
func (m *SeverListHero) String() string { return proto.CompactTextString(m) }
func (*SeverListHero) ProtoMessage()    {}
func (*SeverListHero) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{18}
}

func (m *SeverListHero) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeverListHero.Unmarshal(m, b)
}
func (m *SeverListHero) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeverListHero.Marshal(b, m, deterministic)
}
func (m *SeverListHero) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeverListHero.Merge(m, src)
}
func (m *SeverListHero) XXX_Size() int {
	return xxx_messageInfo_SeverListHero.Size(m)
}
func (m *SeverListHero) XXX_DiscardUnknown() {
	xxx_messageInfo_SeverListHero.DiscardUnknown(m)
}

var xxx_messageInfo_SeverListHero proto.InternalMessageInfo

func (m *SeverListHero) GetList() []*ServerListHeroElement {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *SeverListHero) GetMaxLevelElement() *ServerListHeroElement {
	if m != nil {
		return m.MaxLevelElement
	}
	return nil
}

//邮件列表
type ServerMail struct {
	List                 map[uint64]*GameMailNode `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ServerMail) Reset()         { *m = ServerMail{} }
func (m *ServerMail) String() string { return proto.CompactTextString(m) }
func (*ServerMail) ProtoMessage()    {}
func (*ServerMail) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{19}
}

func (m *ServerMail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerMail.Unmarshal(m, b)
}
func (m *ServerMail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerMail.Marshal(b, m, deterministic)
}
func (m *ServerMail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerMail.Merge(m, src)
}
func (m *ServerMail) XXX_Size() int {
	return xxx_messageInfo_ServerMail.Size(m)
}
func (m *ServerMail) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerMail.DiscardUnknown(m)
}

var xxx_messageInfo_ServerMail proto.InternalMessageInfo

func (m *ServerMail) GetList() map[uint64]*GameMailNode {
	if m != nil {
		return m.List
	}
	return nil
}

type RoleName struct {
	Name                 []byte   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PlayerId             uint64   `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleName) Reset()         { *m = RoleName{} }
func (m *RoleName) String() string { return proto.CompactTextString(m) }
func (*RoleName) ProtoMessage()    {}
func (*RoleName) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{20}
}

func (m *RoleName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleName.Unmarshal(m, b)
}
func (m *RoleName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleName.Marshal(b, m, deterministic)
}
func (m *RoleName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleName.Merge(m, src)
}
func (m *RoleName) XXX_Size() int {
	return xxx_messageInfo_RoleName.Size(m)
}
func (m *RoleName) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleName.DiscardUnknown(m)
}

var xxx_messageInfo_RoleName proto.InternalMessageInfo

func (m *RoleName) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *RoleName) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

//服务器状态阈值设定
type ServerStatus struct {
	Liuchang             uint32   `protobuf:"varint,1,opt,name=liuchang,proto3" json:"liuchang,omitempty"`
	Huobao               uint32   `protobuf:"varint,2,opt,name=huobao,proto3" json:"huobao,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerStatus) Reset()         { *m = ServerStatus{} }
func (m *ServerStatus) String() string { return proto.CompactTextString(m) }
func (*ServerStatus) ProtoMessage()    {}
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_28e5a3290f0e6e17, []int{21}
}

func (m *ServerStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerStatus.Unmarshal(m, b)
}
func (m *ServerStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerStatus.Marshal(b, m, deterministic)
}
func (m *ServerStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerStatus.Merge(m, src)
}
func (m *ServerStatus) XXX_Size() int {
	return xxx_messageInfo_ServerStatus.Size(m)
}
func (m *ServerStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ServerStatus proto.InternalMessageInfo

func (m *ServerStatus) GetLiuchang() uint32 {
	if m != nil {
		return m.Liuchang
	}
	return 0
}

func (m *ServerStatus) GetHuobao() uint32 {
	if m != nil {
		return m.Huobao
	}
	return 0
}

func init() {
	proto.RegisterEnum("Adoter.Asset.MSG_TYPE", MSG_TYPE_name, MSG_TYPE_value)
	proto.RegisterEnum("Adoter.Asset.MERGE_ZONE_TYPE", MERGE_ZONE_TYPE_name, MERGE_ZONE_TYPE_value)
	proto.RegisterEnum("Adoter.Asset.UPDATE_PERIOD_TYPE", UPDATE_PERIOD_TYPE_name, UPDATE_PERIOD_TYPE_value)
	proto.RegisterEnum("Adoter.Asset.SKILL_ADDON_FROM_TYPE", SKILL_ADDON_FROM_TYPE_name, SKILL_ADDON_FROM_TYPE_value)
	proto.RegisterEnum("Adoter.Asset.POSITION_TYPE", POSITION_TYPE_name, POSITION_TYPE_value)
	proto.RegisterEnum("Adoter.Asset.PLAYER_STATUS", PLAYER_STATUS_name, PLAYER_STATUS_value)
	proto.RegisterEnum("Adoter.Asset.GPULevel", GPULevel_name, GPULevel_value)
	proto.RegisterType((*MsgItem)(nil), "Adoter.Asset.MsgItem")
	proto.RegisterType((*MsgItems)(nil), "Adoter.Asset.MsgItems")
	proto.RegisterType((*FamilyName)(nil), "Adoter.Asset.FamilyName")
	proto.RegisterType((*WomanName)(nil), "Adoter.Asset.WomanName")
	proto.RegisterType((*ManName)(nil), "Adoter.Asset.ManName")
	proto.RegisterType((*WhiteList)(nil), "Adoter.Asset.WhiteList")
	proto.RegisterType((*BlackList)(nil), "Adoter.Asset.BlackList")
	proto.RegisterType((*EventPara)(nil), "Adoter.Asset.EventPara")
	proto.RegisterType((*MergeZoneElement)(nil), "Adoter.Asset.MergeZoneElement")
	proto.RegisterType((*World)(nil), "Adoter.Asset.World")
	proto.RegisterType((*MailCache)(nil), "Adoter.Asset.MailCache")
	proto.RegisterType((*BanPlayerList)(nil), "Adoter.Asset.BanPlayerList")
	proto.RegisterType((*Redis_BanChat)(nil), "Adoter.Asset.Redis_BanChat")
	proto.RegisterType((*OnlineStatistics)(nil), "Adoter.Asset.OnlineStatistics")
	proto.RegisterType((*ActivityCache)(nil), "Adoter.Asset.ActivityCache")
	proto.RegisterMapType((map[uint64]*ActivityElement)(nil), "Adoter.Asset.ActivityCache.ListEntry")
	proto.RegisterType((*PlayerChat)(nil), "Adoter.Asset.PlayerChat")
	proto.RegisterType((*PlayerProp)(nil), "Adoter.Asset.PlayerProp")
	proto.RegisterType((*ServerListHeroElement)(nil), "Adoter.Asset.ServerListHeroElement")
	proto.RegisterType((*SeverListHero)(nil), "Adoter.Asset.SeverListHero")
	proto.RegisterType((*ServerMail)(nil), "Adoter.Asset.ServerMail")
	proto.RegisterMapType((map[uint64]*GameMailNode)(nil), "Adoter.Asset.ServerMail.ListEntry")
	proto.RegisterType((*RoleName)(nil), "Adoter.Asset.RoleName")
	proto.RegisterType((*ServerStatus)(nil), "Adoter.Asset.ServerStatus")
}

func init() { proto.RegisterFile("P_Server.proto", fileDescriptor_28e5a3290f0e6e17) }

var fileDescriptor_28e5a3290f0e6e17 = []byte{
	// 1910 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x58, 0x5b, 0x6f, 0xdb, 0xc8,
	0x15, 0x5e, 0xea, 0xae, 0x13, 0xcb, 0x1e, 0x8f, 0x63, 0x5b, 0x71, 0xe2, 0xac, 0xa1, 0xdd, 0x06,
	0x86, 0x0b, 0x18, 0x45, 0x76, 0xb1, 0xe9, 0x1d, 0xa0, 0xa5, 0x89, 0xcd, 0x84, 0x22, 0x05, 0x92,
	0xb6, 0xeb, 0xbc, 0x10, 0xb4, 0x38, 0x96, 0x08, 0x8b, 0xa4, 0x40, 0xd2, 0xde, 0x55, 0x1f, 0xfb,
	0xb6, 0x3f, 0xa1, 0xe8, 0x5b, 0xfb, 0x07, 0x7a, 0xbf, 0xdf, 0x81, 0xfe, 0x82, 0xfe, 0x0b, 0x03,
	0x7d, 0xee, 0x6b, 0x31, 0x33, 0xa4, 0x1c, 0x52, 0x4a, 0x50, 0xec, 0x1b, 0xe7, 0xfb, 0xce, 0x39,
	0xf3, 0xcd, 0x99, 0x73, 0xce, 0x08, 0x82, 0xd5, 0x81, 0x6d, 0xd2, 0xe8, 0x96, 0x46, 0x87, 0xd3,
	0x28, 0x4c, 0x42, 0xbc, 0x22, 0xbb, 0x61, 0x42, 0xa3, 0x43, 0x39, 0x8e, 0x69, 0xb2, 0x83, 0x8e,
	0x1d, 0x9f, 0x76, 0x43, 0xdf, 0x0f, 0x03, 0xc1, 0xef, 0xac, 0x33, 0xa4, 0x4f, 0xe3, 0xd8, 0x19,
	0x51, 0x01, 0x75, 0xfe, 0x2d, 0x41, 0xbd, 0x1f, 0x8f, 0x94, 0x84, 0xfa, 0x78, 0x17, 0xc0, 0x17,
	0xa4, 0xed, 0xb9, 0x6d, 0x69, 0x4f, 0xda, 0x2f, 0x1b, 0xcd, 0x14, 0x51, 0x5c, 0xbc, 0x09, 0xb5,
	0x64, 0x36, 0xa5, 0x76, 0xd2, 0x2e, 0xed, 0x49, 0xfb, 0x55, 0xa3, 0xca, 0x56, 0x16, 0xde, 0x81,
	0xc6, 0x34, 0xf2, 0xc2, 0xc8, 0x4b, 0x66, 0xed, 0x32, 0x27, 0xe6, 0x6b, 0xbc, 0x05, 0xb5, 0x98,
	0x06, 0x2e, 0x8d, 0xda, 0x15, 0x1e, 0x2d, 0x5d, 0x31, 0x9f, 0x88, 0x0e, 0xa9, 0x77, 0x4b, 0xa3,
	0x76, 0x95, 0x33, 0xf3, 0x35, 0xc6, 0x50, 0x49, 0x3c, 0x9f, 0xb6, 0x6b, 0x3c, 0x16, 0xff, 0xc6,
	0x0f, 0xa1, 0xea, 0xd2, 0x89, 0x33, 0x6b, 0xd7, 0xc5, 0xce, 0x7c, 0x81, 0xdb, 0x50, 0x1f, 0x86,
	0x41, 0x42, 0x83, 0xa4, 0xdd, 0xd8, 0x93, 0xf6, 0x57, 0x8c, 0x6c, 0xd9, 0x79, 0x01, 0x8d, 0xf4,
	0x50, 0x31, 0xfe, 0x3a, 0x54, 0x3d, 0xf6, 0xd1, 0x96, 0xf6, 0xca, 0xfb, 0x0f, 0x9e, 0x6f, 0x1e,
	0xbe, 0x9d, 0xa4, 0xc3, 0xd4, 0xcc, 0x10, 0x36, 0x9d, 0x3d, 0x80, 0x97, 0x8e, 0xef, 0x4d, 0x66,
	0x9a, 0xe3, 0x53, 0x26, 0x25, 0x70, 0x7c, 0xca, 0x3d, 0x57, 0x0c, 0xfe, 0xdd, 0xf9, 0x10, 0x9a,
	0xe7, 0xa1, 0xef, 0x04, 0xef, 0x34, 0xd8, 0x85, 0x7a, 0xff, 0x3d, 0xf4, 0xf7, 0xa1, 0x79, 0x3e,
	0xf6, 0x12, 0xaa, 0x7a, 0x71, 0xc2, 0x0c, 0xc2, 0x29, 0x0d, 0x78, 0xae, 0x1b, 0x06, 0xff, 0x66,
	0xb7, 0xe0, 0x4d, 0x6d, 0xc7, 0x75, 0x23, 0x1a, 0xc7, 0xed, 0x12, 0x77, 0x6d, 0x7a, 0x53, 0x59,
	0x00, 0xcc, 0xff, 0x68, 0xe2, 0x0c, 0xaf, 0xbf, 0xaa, 0x7f, 0x17, 0x9a, 0xe4, 0x96, 0x06, 0xc9,
	0xc0, 0x89, 0x1c, 0xbc, 0x0d, 0x75, 0x76, 0xee, 0xfb, 0xeb, 0xae, 0xb1, 0xa5, 0xe2, 0xf2, 0x20,
	0x8c, 0x18, 0x86, 0x37, 0x81, 0xb8, 0xef, 0xb2, 0xd1, 0x64, 0x48, 0x97, 0x01, 0x1d, 0x1f, 0x50,
	0x9f, 0x46, 0x23, 0xfa, 0x26, 0x0c, 0x28, 0x99, 0x50, 0x9f, 0x06, 0x09, 0xfe, 0x2e, 0xab, 0x9e,
	0x68, 0x44, 0x6d, 0x56, 0x16, 0x3c, 0xdc, 0xea, 0xf3, 0xdd, 0x42, 0xb2, 0x89, 0x71, 0x4c, 0xec,
	0x37, 0xba, 0x46, 0x6c, 0xeb, 0x62, 0x40, 0x58, 0x71, 0x45, 0x23, 0x6a, 0xcd, 0xa6, 0x14, 0x3f,
	0x86, 0xe6, 0x0f, 0xc3, 0x80, 0xda, 0x13, 0x2f, 0x4e, 0xb8, 0xe8, 0xb2, 0xd1, 0x60, 0x00, 0x3b,
	0x66, 0xe7, 0x5f, 0x65, 0xa8, 0x9e, 0x87, 0xd1, 0xc4, 0x65, 0x82, 0xb9, 0x59, 0x2a, 0xb8, 0x6a,
	0xd4, 0xd8, 0x52, 0x71, 0xf1, 0x33, 0x58, 0xbb, 0x99, 0xba, 0x4e, 0x42, 0x6d, 0xd7, 0x99, 0xd9,
	0xbc, 0x80, 0x44, 0x95, 0xb6, 0x04, 0xdc, 0x73, 0x66, 0x16, 0xab, 0xa4, 0x7d, 0x40, 0xa9, 0xdd,
	0xe7, 0x94, 0x5e, 0x0b, 0x43, 0x51, 0xb5, 0xab, 0x02, 0x3f, 0xa7, 0xf4, 0x9a, 0x5b, 0x1e, 0xc0,
	0x7a, 0x6a, 0xe9, 0x87, 0x41, 0x32, 0x16, 0xa6, 0x15, 0x6e, 0x9a, 0x6e, 0xd5, 0x67, 0x38, 0xb7,
	0xdd, 0x83, 0x95, 0x2b, 0x2f, 0x8a, 0x13, 0xfb, 0xf2, 0x66, 0x66, 0xc7, 0x01, 0xaf, 0xe9, 0xaa,
	0x01, 0x1c, 0x3b, 0xba, 0x99, 0x99, 0x01, 0x3b, 0xdf, 0x65, 0x38, 0x4b, 0xf3, 0x59, 0x13, 0x25,
	0x7f, 0x19, 0xce, 0x78, 0x3a, 0x59, 0xb6, 0x47, 0x5e, 0x34, 0x49, 0xd9, 0xba, 0xc8, 0x36, 0x43,
	0x04, 0xbd, 0x0f, 0x88, 0xdd, 0xac, 0x1d, 0xf3, 0x5e, 0x17, 0x42, 0x1a, 0x42, 0x33, 0xc3, 0xc5,
	0x08, 0xe0, 0x3a, 0x3e, 0x83, 0x6d, 0x86, 0xa4, 0x86, 0x41, 0x98, 0x78, 0x57, 0xd9, 0x9e, 0x4d,
	0xee, 0xb0, 0x79, 0x4f, 0x6b, 0x9c, 0x15, 0x3b, 0x7c, 0x2f, 0xbb, 0x3b, 0x9e, 0x7e, 0xe0, 0x8d,
	0xf2, 0xb4, 0x70, 0x77, 0x85, 0xfb, 0x4e, 0x2f, 0x8f, 0x97, 0xe1, 0x33, 0x58, 0x13, 0xee, 0xfc,
	0x6e, 0xb8, 0xbe, 0x07, 0x22, 0xf9, 0x7e, 0xe6, 0xc5, 0xe4, 0x75, 0x5e, 0x40, 0xb3, 0xef, 0x78,
	0x93, 0xae, 0x33, 0x1c, 0xb3, 0xfc, 0x56, 0xf8, 0x6e, 0xa2, 0x2d, 0xb7, 0xf2, 0xbb, 0x99, 0x34,
	0x70, 0x99, 0xa9, 0xc1, 0x6d, 0x3a, 0x1f, 0x41, 0xeb, 0xc8, 0x09, 0x06, 0x13, 0x67, 0x46, 0xa3,
	0xac, 0xf0, 0xe7, 0xce, 0xe5, 0xd4, 0xe8, 0x15, 0xb4, 0x0c, 0xea, 0x7a, 0xb1, 0x7d, 0xe4, 0x04,
	0xdd, 0xb1, 0x93, 0xb0, 0x9c, 0x4f, 0xb9, 0xcb, 0x7d, 0x7d, 0x37, 0x04, 0xa0, 0xb8, 0xf8, 0x09,
	0x34, 0x99, 0xd0, 0x38, 0x71, 0xfc, 0x69, 0x5a, 0x2a, 0xf7, 0x40, 0x27, 0x00, 0xa4, 0x07, 0x13,
	0x2f, 0xa0, 0x66, 0xe2, 0x24, 0x5e, 0x9c, 0x78, 0xc3, 0x18, 0x1f, 0xc2, 0x46, 0xc8, 0x31, 0x3b,
	0x8d, 0x2a, 0x12, 0x2b, 0x02, 0xaf, 0x0b, 0x4a, 0x48, 0x14, 0x49, 0x3d, 0x80, 0x14, 0xb4, 0x93,
	0x30, 0x71, 0x26, 0xf7, 0x45, 0x59, 0x36, 0xd6, 0x04, 0x61, 0x31, 0x9c, 0x67, 0xe6, 0xa7, 0x12,
	0xb4, 0xe4, 0x61, 0xe2, 0xdd, 0x7a, 0xc9, 0x4c, 0xa4, 0xe7, 0x5b, 0xb9, 0xf4, 0x7c, 0x2d, 0x9f,
	0x9e, 0x9c, 0xe9, 0x21, 0xcb, 0x08, 0x09, 0x92, 0x68, 0x26, 0x12, 0xb1, 0x73, 0x06, 0xcd, 0x39,
	0x84, 0x11, 0x94, 0xaf, 0xe9, 0x8c, 0xab, 0xac, 0x18, 0xec, 0x13, 0x7f, 0x02, 0xd5, 0x5b, 0x67,
	0x72, 0x23, 0xb4, 0x3c, 0x28, 0xf6, 0x68, 0x16, 0x3a, 0xbb, 0x66, 0x61, 0xfb, 0xed, 0xd2, 0x37,
	0xa5, 0xce, 0xa7, 0x00, 0xe9, 0xf9, 0x58, 0x76, 0x9f, 0xe5, 0x04, 0xe2, 0x7c, 0x14, 0x66, 0x91,
	0x5e, 0xcb, 0x7f, 0x4b, 0x99, 0xdb, 0x20, 0x0a, 0xa7, 0xf8, 0x05, 0x34, 0xa6, 0x61, 0xec, 0x25,
	0x5e, 0x18, 0xa4, 0x43, 0xe2, 0x71, 0xde, 0x75, 0xa0, 0x9b, 0x8a, 0xa5, 0xe8, 0x9a, 0x18, 0x11,
	0x73, 0x63, 0xd6, 0xfa, 0x51, 0x18, 0xf2, 0x59, 0x25, 0x92, 0x58, 0x63, 0x4b, 0xc5, 0xc5, 0x9f,
	0x42, 0x73, 0x12, 0x3a, 0xae, 0x98, 0x3b, 0x65, 0x1e, 0x72, 0x3b, 0x1f, 0x52, 0xd5, 0xe5, 0x5e,
	0x1a, 0x8e, 0x59, 0xf2, 0x81, 0xd3, 0x83, 0xb5, 0x91, 0xe3, 0x53, 0x3b, 0x9c, 0xd2, 0xc8, 0x8e,
	0x13, 0x27, 0x11, 0xcd, 0xbd, 0xfa, 0xfc, 0x49, 0xde, 0xf7, 0x58, 0xee, 0x13, 0x5b, 0x1f, 0x10,
	0x43, 0x04, 0x68, 0x31, 0x27, 0x7d, 0x4a, 0x23, 0x56, 0x18, 0x14, 0x7f, 0x0c, 0xab, 0x53, 0xc7,
	0x13, 0x41, 0x44, 0x39, 0x88, 0xd6, 0x5f, 0x99, 0x3a, 0x1e, 0xb3, 0x9a, 0xf7, 0xf7, 0xd8, 0x89,
	0xed, 0xc4, 0x0b, 0x46, 0xd4, 0xe5, 0xdd, 0xdf, 0x30, 0x9a, 0x63, 0x27, 0xb6, 0x38, 0xc0, 0xde,
	0xb1, 0xf0, 0xea, 0x8a, 0x15, 0x04, 0xef, 0xfd, 0x86, 0x91, 0x2d, 0x59, 0x63, 0xdd, 0x86, 0xde,
	0x90, 0xda, 0x3e, 0xf5, 0x2f, 0x45, 0x1d, 0x37, 0xf8, 0xd9, 0x5b, 0x1c, 0xee, 0x73, 0x54, 0x71,
	0xd9, 0xfb, 0x78, 0x49, 0xbd, 0xc9, 0x6d, 0xda, 0xe5, 0x62, 0xd1, 0xf9, 0xb9, 0x04, 0x9b, 0x62,
	0x38, 0xb0, 0x72, 0x38, 0xa1, 0x51, 0x98, 0xcd, 0xea, 0x36, 0xd4, 0x9d, 0xe1, 0x7d, 0xf9, 0xae,
	0x18, 0xd9, 0x32, 0xdf, 0x33, 0x25, 0x5e, 0x34, 0xf7, 0x3d, 0xb3, 0x0d, 0xf5, 0x31, 0x8d, 0x42,
	0x46, 0x89, 0x99, 0x59, 0x63, 0x4b, 0xf1, 0x5c, 0x70, 0x62, 0x42, 0x6f, 0xe9, 0x24, 0x1d, 0x92,
	0x4d, 0x86, 0xa8, 0x0c, 0x60, 0xf2, 0xae, 0x22, 0xf6, 0x10, 0x8a, 0xe4, 0x88, 0x05, 0xeb, 0xe1,
	0xf8, 0xda, 0x0b, 0xb2, 0x87, 0x9e, 0x7d, 0x77, 0x7e, 0x2c, 0x41, 0xcb, 0xa4, 0x6f, 0x29, 0xc6,
	0x2f, 0x72, 0x65, 0xf6, 0x51, 0x71, 0x4c, 0x2c, 0x39, 0x9d, 0xa8, 0x3b, 0xac, 0xc3, 0xba, 0xef,
	0x7c, 0x21, 0x24, 0xd9, 0x54, 0x50, 0x69, 0xc9, 0xff, 0x5f, 0x51, 0xd6, 0x7c, 0xe7, 0x0b, 0x2e,
	0x3f, 0x05, 0x98, 0x36, 0x10, 0xa6, 0x6c, 0x32, 0xe1, 0xcf, 0x72, 0xc2, 0x3a, 0xcb, 0x42, 0x32,
	0xbb, 0x85, 0xee, 0x34, 0xdf, 0xdf, 0x9d, 0xdf, 0xc8, 0x77, 0xe7, 0x4e, 0xa1, 0x1a, 0xd9, 0x0f,
	0x38, 0xc7, 0x9b, 0x68, 0xa1, 0x4b, 0xdf, 0x6e, 0xcd, 0xef, 0x40, 0xc3, 0x08, 0x27, 0xb4, 0xf0,
	0xab, 0x43, 0xca, 0x7e, 0x75, 0xbc, 0xf7, 0x5a, 0x3b, 0x47, 0xb0, 0x22, 0xf4, 0xb2, 0x9a, 0xbe,
	0x89, 0xd9, 0xaf, 0xb3, 0x89, 0x77, 0x33, 0x1c, 0x3b, 0xc1, 0x88, 0x07, 0x69, 0x19, 0xf3, 0x35,
	0xfb, 0x45, 0x37, 0xbe, 0x09, 0x2f, 0x9d, 0x90, 0x47, 0x69, 0x19, 0xe9, 0xea, 0xe0, 0x27, 0x15,
	0x68, 0xf4, 0xcd, 0x63, 0xde, 0x24, 0x78, 0x13, 0xd6, 0xb3, 0x6f, 0x5b, 0xd6, 0x15, 0x5b, 0x3b,
	0x55, 0x55, 0xf4, 0x01, 0x6e, 0x03, 0xce, 0xc1, 0x44, 0xb3, 0x88, 0x81, 0x7e, 0x71, 0x27, 0x2d,
	0x30, 0x2a, 0x91, 0xcf, 0x08, 0xfa, 0xe5, 0x9d, 0x84, 0xb7, 0x0b, 0xa1, 0xfa, 0xfa, 0x19, 0x41,
	0xbf, 0xba, 0x93, 0xf0, 0x23, 0xd8, 0x98, 0x13, 0x27, 0x44, 0x36, 0x2c, 0xfb, 0x88, 0xc8, 0x16,
	0xfa, 0x75, 0xc1, 0xe7, 0xb5, 0xd2, 0x7d, 0x6d, 0xeb, 0xa7, 0x16, 0xfa, 0xcd, 0x9d, 0x84, 0x9f,
	0x42, 0x7b, 0x4e, 0xf4, 0x89, 0x25, 0xdb, 0x3d, 0xd3, 0xee, 0x13, 0xd3, 0x94, 0x8f, 0x09, 0xfa,
	0x6d, 0x41, 0x06, 0xe7, 0xfb, 0xb2, 0xa2, 0xa2, 0xdf, 0xdd, 0x49, 0x78, 0x07, 0x1e, 0xce, 0x19,
	0x2e, 0xce, 0x56, 0xc9, 0x19, 0x51, 0xd1, 0xef, 0xef, 0x24, 0xfc, 0x04, 0xb6, 0x0a, 0x5c, 0xef,
	0x54, 0x3b, 0x26, 0xba, 0x86, 0xfe, 0x70, 0x27, 0xe1, 0x5d, 0xd8, 0x9e, 0xb3, 0x86, 0xae, 0xf7,
	0x6d, 0xd3, 0x92, 0x0d, 0x8b, 0x4d, 0x15, 0xf4, 0xc7, 0xc2, 0x96, 0x26, 0xd1, 0x7a, 0x62, 0xcb,
	0x3f, 0x15, 0x18, 0x9e, 0x29, 0xee, 0xf3, 0xe7, 0x82, 0x98, 0x97, 0x86, 0xc2, 0xbc, 0xd8, 0x80,
	0x42, 0x7f, 0x29, 0x88, 0xe1, 0x5e, 0x73, 0x31, 0x7f, 0x2d, 0x78, 0x0a, 0x56, 0x1c, 0xe3, 0x6f,
	0x77, 0x12, 0xfe, 0x10, 0x1e, 0xbd, 0x75, 0x8c, 0x33, 0xa2, 0xda, 0x26, 0xb1, 0x2c, 0x95, 0xf4,
	0x89, 0x66, 0xa1, 0xbf, 0x17, 0x9c, 0xbb, 0x27, 0xb2, 0x76, 0x4c, 0x6c, 0x55, 0xd1, 0x08, 0xfa,
	0x47, 0xe1, 0x94, 0xe7, 0xaf, 0x5e, 0xbd, 0x4a, 0x23, 0x28, 0x3d, 0x13, 0xfd, 0xf3, 0x4e, 0x3a,
	0xf8, 0x51, 0x09, 0xd6, 0x0a, 0x3f, 0xfe, 0x70, 0x1b, 0x1e, 0x16, 0xa0, 0xfb, 0x3a, 0x59, 0x60,
	0x0c, 0x59, 0x7b, 0x8d, 0xa4, 0x65, 0x4c, 0x57, 0x95, 0x35, 0x54, 0xc2, 0x8f, 0x60, 0xb3, 0xc8,
	0x0c, 0x64, 0xc3, 0xba, 0x40, 0x65, 0xbc, 0x0d, 0x1b, 0x0b, 0xd4, 0xd9, 0x00, 0x55, 0xf0, 0x63,
	0xd8, 0x2e, 0x12, 0xaa, 0x22, 0x6b, 0x17, 0x8a, 0x86, 0xaa, 0x78, 0x17, 0x1e, 0x15, 0xc9, 0x13,
	0x5d, 0xd3, 0x8d, 0x73, 0x59, 0x55, 0x51, 0x6d, 0xa9, 0x92, 0x13, 0xd9, 0x42, 0xf5, 0x65, 0xdb,
	0x1d, 0xc9, 0x1a, 0x6a, 0x1c, 0x7c, 0x29, 0x01, 0x3e, 0x1d, 0xf4, 0x64, 0x8b, 0xd8, 0x03, 0x62,
	0x28, 0xba, 0x78, 0x92, 0x98, 0x8a, 0x45, 0x34, 0x4b, 0xc5, 0x0e, 0x6c, 0x2d, 0x21, 0x7b, 0xf2,
	0x05, 0x92, 0xde, 0xe1, 0x78, 0xa2, 0x9f, 0x1a, 0xa8, 0xc4, 0xe4, 0x2f, 0x21, 0xbb, 0xa7, 0xa6,
	0xa5, 0xf7, 0x51, 0xf9, 0xe0, 0x67, 0xec, 0x69, 0x78, 0xad, 0xa8, 0xaa, 0x2d, 0xf7, 0x7a, 0xba,
	0x66, 0xbf, 0x34, 0xf4, 0xbe, 0x90, 0xf3, 0x14, 0x76, 0x96, 0x12, 0x99, 0xa2, 0x8f, 0x61, 0x6f,
	0x39, 0x2f, 0xd0, 0xae, 0x6c, 0xf4, 0x90, 0xf4, 0x6e, 0x2b, 0xf2, 0x03, 0xa6, 0x87, 0x68, 0x5d,
	0x82, 0x4a, 0xef, 0xde, 0x4b, 0xb1, 0x08, 0x53, 0xf9, 0xa5, 0x04, 0xad, 0xdc, 0xcf, 0x01, 0xbc,
	0x05, 0x38, 0x07, 0x64, 0xaa, 0x16, 0x70, 0x22, 0x9b, 0x16, 0x62, 0xa3, 0x60, 0x23, 0x8f, 0x9b,
	0xfa, 0xa9, 0x75, 0x82, 0x4a, 0x8b, 0x0e, 0xe7, 0xc4, 0xb4, 0x44, 0xb1, 0x14, 0x36, 0xd0, 0x0d,
	0xeb, 0x04, 0x55, 0x0e, 0xfe, 0xc3, 0xb4, 0xa8, 0xf2, 0x05, 0x31, 0x58, 0x07, 0x5b, 0xa7, 0x26,
	0x2b, 0xb9, 0x1c, 0x60, 0x2b, 0x9a, 0x62, 0x29, 0x32, 0x93, 0xf3, 0x18, 0xb6, 0xf3, 0x54, 0x57,
	0xd5, 0x4d, 0x72, 0x2e, 0x2b, 0x96, 0x28, 0xe2, 0x25, 0x64, 0x4f, 0xe4, 0x23, 0xcf, 0xa8, 0xba,
	0x69, 0xd9, 0x5d, 0x5d, 0xd3, 0x48, 0x97, 0x89, 0x5b, 0x08, 0x6b, 0x90, 0x8c, 0xac, 0x2c, 0x86,
	0xd5, 0x35, 0xde, 0x9e, 0xd5, 0x45, 0xa1, 0x03, 0xa2, 0xf5, 0x14, 0xed, 0x58, 0x94, 0x71, 0xf1,
	0x0c, 0x7c, 0xcc, 0xd4, 0x0f, 0x7a, 0xd0, 0x38, 0x1e, 0x9c, 0x8a, 0xf7, 0x7b, 0x1d, 0x5a, 0xd9,
	0xb7, 0x7d, 0xe2, 0x8d, 0xc6, 0xe8, 0x03, 0xbc, 0x01, 0x6b, 0x73, 0xa8, 0xef, 0xb9, 0xde, 0x8d,
	0x8f, 0x24, 0x8c, 0x60, 0x65, 0x0e, 0xaa, 0xe1, 0xe7, 0xa8, 0x74, 0x54, 0x7b, 0x53, 0xf1, 0x1d,
	0x2f, 0xb8, 0xac, 0xf1, 0x7f, 0x1b, 0x3e, 0xf9, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x0c,
	0xd9, 0xe2, 0xb2, 0x10, 0x00, 0x00,
}
